name: webscrapping
on:
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the respository
      uses: actions/checkout@v3
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Download library 
      run: pip install -r requirements.txt
    - name: Run the Python code
      run: python3 main.py
    - name: auto-push to github
      if: always()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git diff-index --quiet HEAD || git commit -am "archived"
        git push
