name: webscraping_v3

on:
  workflow_dispatch:
  schedule:
    - cron: '1 16 * * 4'  # Runs every Thursday at 12:01 am Hong Kong time (UTC+8)

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Download library
        run: pip install -r requirements.txt

      - name: Run the Python code
        run: python3 hse28.py hse28_resmaster.csv 

      - name: Create a new repository for hse28_test.csv
        run: |
          mkdir hse28_test_repository
          cd hse28_test_repository
          git init
          touch hse28_test.csv
          git add hse28_test.csv
          git commit -m "Add hse28_test.csv"
          git remote add origin https://github.com/your-username/hse28_test_repository.git
          git push -u origin master
